Numpy

numpy is a fundamental library for scientific computing in python.

In [1]:
!pip install numpy

In [2]:
import numpy as np

## create array using numpy 
##create a 1 D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
#1D array
arr2 = np.array([1,2,3,4,5])
arr2.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [4]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [5]:
#2D array
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2.shape

(2, 5)

In [6]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
## identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
#attributes of Numpy Array
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape:",arr.shape)
print("Number of dimensions:",arr.ndim)
print("size (number of elements):",arr.size)
print("Data type:",arr.dtype)
print("Item size (in bytes):",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [10]:
#Numpy vectorized operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

###Element wise addition
print("Addition:",arr1+arr2)

## Element wise Subtraction 
print("Subtraction:",arr1-arr2)

## Element wise Multiplication 
print("Subtraction:",arr1*arr2)

## Element wise division
print("Subtraction:",arr1 / arr2)


Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Subtraction: [ 10  40  90 160 250]
Subtraction: [0.1 0.1 0.1 0.1 0.1]


In [11]:
#  Universal Function 
arr = np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

#sine
print(np.sin(arr))

#natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [12]:
## array licing and Indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [14]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [15]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [16]:
## Modify array elements
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [17]:
arr[1:] = 99
print(arr)

[[100   2   3   4]
 [ 99  99  99  99]
 [ 99  99  99  99]]


In [18]:
### statitical concepts--Normalization
## To have mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:",normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [19]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

#Mean
mean = np.mean(data)
print("Mean:",mean)

#Median 
median = np.median(data)
print("Median:",median)

#Standard deviation
std_dev = np.std(data)
print("standard Deviation:",std_dev)

#Variance
variance = np.var(data)
print("Variance:",variance)

Mean: 5.5
Median: 5.5
standard Deviation: 2.8722813232690143
Variance: 8.25


In [20]:
## Logical Operation
data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>5) & (data <= 8)]

array([6, 7, 8])